# Constant Types
For more about the constants please follow: https://www.tensorflow.org/api_guides/python/constant_op


You can create constants of scalar or tensor values.
> `tf​.​constant​(​value​,​ dtype​=​None​,​ shape​=​None​,​ name​=​'Const'​,​ verify_shape​=​False)`

In [2]:
import tensorflow as tf

C:\Program Files\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [18]:
# created this function to evaluate the expression and print the result.
# like should not be done in production
def run_print(x):
    with tf.Session() as sess:
        print(sess.run(x))

#### Constant of 1d tensor (vector)

In [15]:
a = tf.constant([2,2], name="vector")
run_print(a)

[2 2]


#### Constant of 2x2 tensor (matrix)

In [14]:
b = tf.constant([[0,1],[2,3]],name="b")
run_print(b)

[[0 1]
 [2 3]]


### You can create tensors whose elements are of a specific value
Note the similarity to numpy.zeros, numpy.zeros_like, numpy.ones, numpy.ones_like.
####  Create a tensor of shape and all elements are zeros
> `tf.zeros(input_tensor, dtype=None, name=None)`


In [16]:
zeros_tensor = tf.zeros([3,4],tf.int32,name='zeros_tensor')

In [17]:
run_print(zeros_tensor)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


#### Create a tensor of shape and type (unless type is specified) as the input_tensor but all elements are zeros.
> `tf.zeros_like(input_tensor, dtype=None, name=None, optimize=True)`


In [20]:
zero_b = tf.zeros_like(b)
run_print(zero_b)

[[0 0]
 [0 0]]


#### Create a tensor of shape and all elements are ones
> `tf.ones(input_tensor, dtype=None, name=None)`


In [21]:
ones_tensor = tf.ones([4, 7], tf.int32)
run_print(ones_tensor)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


#### Create a tensor of shape and type (unless type is specified) as the input_tensor but all elements are ones.
> `tf.ones_like(input_tensor, dtype=None, name=None, optimize=True)`


In [22]:
ones_b = tf.ones_like(b)
run_print(ones_b)

[[1 1]
 [1 1]]


#### Create a tensor filled with a scalar value.
> `tf.fill(dims, value, name=None)`

In [24]:
run_print(tf.fill([3,2],8,name='all8'))

[[8 8]
 [8 8]
 [8 8]]


### Sequences
> `tf.linspace(start, stop, num, name=None)`

Create a sequence of num evenly-spaced values are generated beginning at start. If num > 1, the values in the sequence increase by stop - start / num - 1, so that the last one is exactly stop.
* Start, stop, num must be scalars
* Comparable to but slightly different from numpy.linspace

> `numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)`

In [26]:
run_print(tf.linspace(10.0, 13.0, 4, name="linspace"))

[10. 11. 12. 13.]


### Range
> `tf.range(start, limit=None, delta=1, dtype=None, name='range'))`

Create a sequence of numbers that begins at start and extends by increments of delta up to but not including limit
slight different from range in Python

#### 'start' is 3, 'limit' is 18, 'delta' is 3

In [27]:
run_print(tf.range(3,18,3))

[ 3  6  9 12 15]


#### 'start' is 3, 'limit' is 1, 'delta' is -0.5


In [28]:
run_print(tf.range(3,1,-0.5))

[3.  2.5 2.  1.5]


#### 'limit' is 5

In [30]:
run_print(tf.range(5))

[0 1 2 3 4]


** Note: **Unlike NumPy or Python sequences, TensorFlow sequences are not iterable.
 

## You can also generate random constants from certain distributions.

> tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)

> tf.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)

> tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)

> tf.random_shuffle(value, seed=None, name=None)

> tf.random_crop(value, size, seed=None, name=None)

> tf.multinomial(logits, num_samples, seed=None, name=None)

> tf.random_gamma(shape, alpha, beta=None, dtype=tf.float32, seed=None, name=None)


### Randomly Generated Constants


> `tf.set_random_seed(seed)`